apiVersion: v1
kind: Pod
metadata:
  name: nginx-db-pod
spec:
  containers:
  - name: nginx-container
    image: nginx
    env:
    - name: MYSQL_USERNAME
      valueFrom:
        secretKeyRef:
          name: db-secret
          key: username
    - name: MYSQL_PASSWORD
      valueFrom:
        secretKeyRef:
          name: db-secret
          key: password
