apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-custom-config
data:
  nginx.conf: |
    server {
        listen 80;
        server_name my-nginx;
        location / {
            root /usr/share/nginx/html;
            index index.html index.htm;
        }
    }

  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>Welcome to My Nginx!</title>
    </head>
    <body>
      <h1>Hello, Nginx has been deployed in EKS Cluster!</h1>
    </body>
    </html>
