apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: nginx
spec:
  containers:
  - name: nginx-container
    image: nginx
    volumeMounts:
    - name: config-volume
      mountPath: /etc/nginx/conf.d
    - name: html-volume
      mountPath: /usr/share/nginx/html
  volumes:
  - name: config-volume
    configMap:
      name: nginx-custom-config
      items:
      - key: nginx.conf
        path: nginx.conf
  - name: html-volume
    configMap:
      name: nginx-custom-config
      items:
      - key: index.html
        path: index.html
