apiVersion: v1
kind: Pod
metadata:
  name: pv-task-pod
spec:
  volumes:
    - name: pv-vol
      persistentVolumeClaim:
        claimName: k8s-pv-claim
  nodeName: k8s-worker-3
  containers:
    - name: pv-pod
      image: nginx
      ports:
        - containerPort: 80
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: pv-vol