apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: wordpress-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: wordpress-4
  minReplicas: 1
  maxReplicas: 5  # Set the maximum number of replicas for scaling
  targetCPUUtilizationPercentage: 50
